#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-spatstat.data
Version  : 3.1.6
Release  : 65
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/spatstat.data_3.1-6.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/spatstat.data_3.1-6.tar.gz
Summary  : Datasets for 'spatstat' Family
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-spatstat.utils
BuildRequires : R-spatstat.utils
BuildRequires : buildreq-R

%description
No detailed description available

%prep
%setup -q -n spatstat.data
pushd ..
cp -a spatstat.data buildavx2
popd
pushd ..
cp -a spatstat.data buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742440768

%install
export SOURCE_DATE_EPOCH=1742440768
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/spatstat.data/CITATION
/usr/lib64/R/library/spatstat.data/DESCRIPTION
/usr/lib64/R/library/spatstat.data/INDEX
/usr/lib64/R/library/spatstat.data/Meta/Rd.rds
/usr/lib64/R/library/spatstat.data/Meta/data.rds
/usr/lib64/R/library/spatstat.data/Meta/features.rds
/usr/lib64/R/library/spatstat.data/Meta/hsearch.rds
/usr/lib64/R/library/spatstat.data/Meta/links.rds
/usr/lib64/R/library/spatstat.data/Meta/nsInfo.rds
/usr/lib64/R/library/spatstat.data/Meta/package.rds
/usr/lib64/R/library/spatstat.data/NAMESPACE
/usr/lib64/R/library/spatstat.data/NEWS
/usr/lib64/R/library/spatstat.data/R/spatstat.data
/usr/lib64/R/library/spatstat.data/R/spatstat.data.rdb
/usr/lib64/R/library/spatstat.data/R/spatstat.data.rdx
/usr/lib64/R/library/spatstat.data/data/Rdata.rdb
/usr/lib64/R/library/spatstat.data/data/Rdata.rds
/usr/lib64/R/library/spatstat.data/data/Rdata.rdx
/usr/lib64/R/library/spatstat.data/doc/packagesizes.txt
/usr/lib64/R/library/spatstat.data/help/AnIndex
/usr/lib64/R/library/spatstat.data/help/aliases.rds
/usr/lib64/R/library/spatstat.data/help/macros/defns.Rd
/usr/lib64/R/library/spatstat.data/help/paths.rds
/usr/lib64/R/library/spatstat.data/help/spatstat.data.rdb
/usr/lib64/R/library/spatstat.data/help/spatstat.data.rdx
/usr/lib64/R/library/spatstat.data/html/00Index.html
/usr/lib64/R/library/spatstat.data/html/R.css
/usr/lib64/R/library/spatstat.data/info/packagesizes.txt
/usr/lib64/R/library/spatstat.data/rawdata/amacrine/amacrine.txt
/usr/lib64/R/library/spatstat.data/rawdata/finpines/finpines.txt
/usr/lib64/R/library/spatstat.data/rawdata/gorillas/vegetation.asc
/usr/lib64/R/library/spatstat.data/rawdata/osteo/osteo36.txt
/usr/lib64/R/library/spatstat.data/rawdata/sandholes/sandholes.jpg
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/activezone.txt
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/mitochondria.txt
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/presynapse.txt
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/vesicles.csv
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/vesicles.txt
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/vesiclesimage.tif
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/vesiclesmask.tif
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/vesicleswindow.csv
/usr/lib64/R/library/spatstat.data/rawdata/vesicles/vesicleswindow.txt
